apiVersion: v1
kind: ServiceAccount
metadata:
  name: apiserver
  namespace: kube-aggregation
---
apiVersion: v1
kind: Service
metadata:
  name: apiserver
  namespace: kube-aggregation
spec:
  ports:
  - port: 443
    name: https
    protocol: TCP
    targetPort: 443
  - port: 2345
    name: dlv
    protocol: TCP
    targetPort: 2345
  selector:
    app: apiserver
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
  namespace: kube-aggregation
  labels:
    app: apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      containers:
      - name: apiserver
        image: apiserver:v1
        command:
        - sh
        - -c
        - sleep 36000
      serviceAccountName: apiserver
